---
# tasks file for ansible-role-bastille
- name: Install bastille pkg
  pkgng:
    name: bastille
    state: latest

- name: Check for any release bootstrapped alreday
  command: bastille list release
  register: release

- name: Bootstrap bastille 
  shell: bastille bootstrap "{{ version }}"
  when: release.rc != 0

- name: Create all continers
  shell: bastille create -V "{{ item.name }}" "{{ version }}" "{{ item.ip }}" em0
  ignore_errors: true
  with_items: 
    - "{{ containers }}"
  tags: build

- name: Bootstrap templates
  shell: bastille bootstrap "{{ item }}"
  ignore_errors: true
  with_items:
    - "{{ templates }}"

- name: Apply template to all containers
  shell: bastille template ALL "{{ item }}"
  ignore_errors: true
  with_items:
    - "{{ apply_templates }}"
  tags: apply
